# Generated by Django 4.2 on 2023-04-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32)),
                ('descripcion', models.TextField(help_text='pon la descripcion de la pelicula', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='pon el nombre del director', max_length=64)),
                ('pelicula', models.ManyToManyField(to='catalogo.pelicula')),
            ],
        ),
    ]
