# Generated by Django 4.2 on 2023-04-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(help_text='pon la descripcion de la pelicula', max_length=500),
        ),
    ]
