# Generated by Django 4.2 on 2023-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_director_peliculas_delete_directores_delete_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='peliculas',
            field=models.ManyToManyField(to='catalogo.peliculas'),
        ),
    ]
